<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDPfjxm4\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDPfjxm4/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDPfjxm4.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDPfjxm4\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDPfjxm4\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'DPfjxm4',
    'container.build_id' => 'd4bbfd50',
    'container.build_time' => 1547554404,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerDPfjxm4');
